#!/usr/bin/env bash

WORKSPACE=${WORKSPACE:-`pwd`}

mkdir ${WORKSPACE}/build
cd ${WORKSPACE}/build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D OPENCV_GENERATE_PKGCONFIG=ON \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D INSTALL_C_EXAMPLES=OFF \
	-D OPENCV_ENABLE_NONFREE=ON \
	-D OPENCV_EXTRA_MODULES_PATH=${WORKSPACE}/opencv_contrib/modules \
	-D PYTHON_DEFAULT_EXECUTABLE=`which python3` \
	-D PYTHON_EXECUTABLE=`which python3` \
	-D PYTHON2_EXECUTABLE=`which python2` \
	-D BUILD_EXAMPLES=off \
	${WORKSPACE}/opencv
