#!/usr/bin/env bash
BUILD_DIR=${BUILD_DIR:-openvc4}
PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE:-`which python3`}

mkdir ${BUILD_DIR}
cd ${BUILD_DIR}

CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER:-`which clang++-8`}
CMAKE_C_COMPILER=${CMAKE_C_COMPILER:-`which clang-8`}


cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/opt/${BUILD_DIR} \
	-D CMAKE_C_COMPILER=${CMAKE_C_COMPILER} \
	-D CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} \
    -D INSTALL_PYTHON_EXAMPLES=ON \
	-D BUILD_EXAMPLES=on \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
	-D PYTHON_DEFAULT_EXECUTABLE=${PYTHON_EXECUTABLE} \
	-D PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} \
    -D PYTHON2_EXECUTABLE=`which python2` \
    ../opencv

exit 0

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_C_COMPILER=${CMAKE_C_COMPILER} \
	-D CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} \
	-D OPENCV_GENERATE_PKGCONFIG=ON \
	-D CMAKE_INSTALL_PREFIX=/opt/${BUILD_DIR} \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D INSTALL_C_EXAMPLES=OFF \
	-D OPENCV_ENABLE_NONFREE=ON \
	-D OPENCV_EXTRA_MODULES_PATH=${WORKSPACE}/../opencv_contrib/modules \
	-D PYTHON_DEFAULT_EXECUTABLE=${PYTHON_EXECUTABLE} \
	-D PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} \
	-D PYTHON2_EXECUTABLE=`which python2` \
	-D BUILD_EXAMPLES=on \
	../opencv

