#!/usr/bin/env bash
WORKSPACE=${WORKSPACE:-`pwd`}

mkdir ${WORKSPACE}/build
cd ${WORKSPACE}/build

CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER:-`which clang++-8`}
CMAKE_C_COMPILER=${CMAKE_C_COMPILER:-`which clang-8`}

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_C_COMPILER=${CMAKE_C_COMPILER} \
    -D CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} \
	-D OPENCV_GENERATE_PKGCONFIG=ON \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D INSTALL_C_EXAMPLES=OFF \
	-D OPENCV_ENABLE_NONFREE=ON \
	-D OPENCV_EXTRA_MODULES_PATH=${WORKSPACE}/opencv_contrib/modules \
	-D PYTHON_DEFAULT_EXECUTABLE=`which python3` \
	-D PYTHON_EXECUTABLE=`which python3` \
	-D PYTHON2_EXECUTABLE=`which python2` \
	-D BUILD_EXAMPLES=off \
	${WORKSPACE}/opencv
